/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gstJNI */

#ifndef _Included_gstJNI
#define _Included_gstJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gstJNI
 * Method:    pipelineLaunch
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gstJNI_pipelineLaunch
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
