/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class template_library_SimpleVideo */

#ifndef _Included_template_library_SimpleVideo
#define _Included_template_library_SimpleVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_template_library_SimpleVideo_gstreamer_1init
  (JNIEnv *, jclass);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_register
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_template_library_SimpleVideo_gstreamer_1register
  (JNIEnv *, jobject);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_loadFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_template_library_SimpleVideo_gstreamer_1loadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_play
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_template_library_SimpleVideo_gstreamer_1play
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_seek
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_template_library_SimpleVideo_gstreamer_1seek
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_set_loop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_template_library_SimpleVideo_gstreamer_1set_1loop
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_get_duration
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_template_library_SimpleVideo_gstreamer_1get_1duration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_get_time
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_template_library_SimpleVideo_gstreamer_1get_1time
  (JNIEnv *, jobject, jlong);

/*
 * Class:     template_library_SimpleVideo
 * Method:    gstreamer_pipeline_launch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_template_library_SimpleVideo_gstreamer_1pipeline_1launch
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
